doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
        driver: pdo_mysql
        server_version: '5.7'
        charset: utf8mb4
        types:
            email: Bookify\Infrastructure\Persistence\Doctrine\Types\EmailType
            datetime: Bookify\Infrastructure\Persistence\Doctrine\Types\DateTimeType
            custom_uuid: Bookify\Infrastructure\Persistence\Doctrine\Types\CustomUuidType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            Bookify:
                type: xml
                dir: '%kernel.project_dir%/src/Bookify/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: Bookify\Domain
                alias: Bookify
                is_bundle: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
