services:
  db:
    container_name: symfony7-template_db
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u ${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - "3306:3306"
    networks:
      - symfony_template_network

  php:
    container_name: symfony7-template_php
    build:
      context: ./php-fpm
      args:
        TIMEZONE: ${TIMEZONE}
        UID: ${UID}
    volumes:
      - ../:/var/www/symfony7-template:cached
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      APP_ENV: dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - symfony_template_network

  nginx:
    container_name: symfony7-template_nginx
    build:
      context: ./nginx
      args:
        UID: ${UID}
    volumes:
      - ../:/var/www/symfony7-template:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
    ports:
      - "8080:80"
    depends_on:
      php:
        condition: service_started
    networks:
      - symfony_template_network

volumes:
  db_data:

networks:
  symfony_template_network:
    driver: bridge
